version: 2.1

orbs:
  kube: twdps/kube-ops@dev:alpha
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@dev:alpha

globals:
  - &context platform
  - &executor-image ghcr.io/twplatformlabs/circleci-eks-ops:alpine-2026.04.3
  - &config-repo twplatformlabs/psk-aws-control-plane-configuration

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: access cluster for testing
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.cluster >>.env
      - kube/op-kubeconfig:
          op-value: platform/<< parameters.cluster>>/kubeconfig-base64
      - do/bash-functions

jobs:

  update metrics-server deployment configuration:
    docker:
      - image: *executor-image
    parameters:
      cluster-role:
        description: cluster role to be updated
        type: string
    steps:
      - checkout
      - op/env
      - run:
          name: generate application resource for role
          command: bash scripts/generate_application_resource.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/*
          destination: "roles/<<parameters.cluster-role>>/metrics-server"
          repository-url: *config-repo

  functional-tests:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to test
        type: string
      cluster-role:
        description: cluster role to be tested
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: run integration test of metrics-server
          command: bash scripts/integration_tests.sh << parameters.cluster >> << parameters.cluster-role >>

workflows:

  deploy sandbox role configuration:
    jobs:
      - update metrics-server deployment configuration:
          name: update sandbox configuration
          context: *context
          cluster-role: sandbox
          filters: *on-push-main

      - functional-tests:
          name: test sandbox clusters
          context: *context
          cluster: sbx-i01-aws-us-east-1
          cluster-role: sandbox
          requires:
            - update sandbox configuration
          filters: *on-push-main
